### ISSUE TITLE
NoSuchElementException Crash with FTBChunks + JourneyMap

### ISSUE THREAD

**Issue by kurisubrooks** [lanAnderson/SeasonInfo#54]
Hello, trying to add SeasonHUD ([Fabric v1.20.1-1.6.4](https://legacy.curseforge.com/minecraft/mc-mods/seasonhud-fabric/files/4941412)) under the modpack [BigChadGuys Plus](https://www.curseforge.com/minecraft/modpacks/bigchadguys-plus) (1.1.5 - 1.20.1) yields the following error. There appears to be an incompatibility between this mod and FTBChunks or the rendering system (Sodium). JourneyMap is the minimap mod that I am using.

Full log and crash: https://mclo.gs/UqHlQuK
List of mods is at [Ln 120](https://mclo.gs/UqHlQuK#L120). Crash log begins at [Ln 3776](https://mclo.gs/UqHlQuK#L3776).

```
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at club.iananderson.seasonhud.client.minimaps.FTBChunks.onHudRender(FTBChunks.java:47)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$dod000$fabric-rendering-v1$render(class_329.java:9886)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

Please let me know if I can be of any assistance.

**Comment by lanAnderson** [comment]
Should be fixed in v1.7.0, which should be out soon
