### ISSUE TITLE
Crash on latest version 1.7.0 [Fabric 0.14.25/1.19.2]

### ISSUE THREAD

**Issue by pokesmells** [lanAnderson/SeasonInfo#56]
```
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'advanced_runtime_resource_pack'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.devtech.arrp.ARRP failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 4 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [server_translations_api.mixin.json:text.MutableTextMixin from mod server_translations_api] from phase [DEFAULT] in config [server_translations_api.mixin.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: server_translations_api.mixin.json:text.MutableTextMixin from mod server_translations_api target net.minecraft.class_5250 was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 19 more

```

Crashes on start-up.

**Comment by Sunconure11** [comment]
It's also causing weird mixin-related errors on Quilt @lanAnderson 

[crash-2023-12-20_13.57.53.5153-quilt_loader.txt](https://github.com/lanAnderson/SeasonHUD/files/13731241/crash-2023-12-20_13.57.53.5153-quilt_loader.txt)
[crash-2023-12-20_14.01.10.7237-quilt_loader.txt](https://github.com/lanAnderson/SeasonHUD/files/13731242/crash-2023-12-20_14.01.10.7237-quilt_loader.txt)
[crash-2023-12-20_13.33.54.4292-quilt_loader.txt](https://github.com/lanAnderson/SeasonHUD/files/13731243/crash-2023-12-20_13.33.54.4292-quilt_loader.txt)
[crash-2023-12-20_13.44.54.0057-quilt_loader.txt](https://github.com/lanAnderson/SeasonHUD/files/13731244/crash-2023-12-20_13.44.54.0057-quilt_loader.txt)
[crash-2023-12-20_13.50.39.7662-quilt_loader.txt](https://github.com/lanAnderson/SeasonHUD/files/13731245/crash-2023-12-20_13.50.39.7662-quilt_loader.txt)
[crash-2023-12-20_13.55.10.3489-quilt_loader.txt](https://github.com/lanAnderson/SeasonHUD/files/13731246/crash-2023-12-20_13.55.10.3489-quilt_loader.txt)

**Comment by lanAnderson** [comment]
From what I can tell it is an issue with Server Translation API (included in Liberty's Villagers) causing it with it's Mixins.  I made a couple changes to the 1.19 version and reuploaded it.  There will be a mixin error in the log, but it shouldn't crash now.
