### ISSUE TITLE
NoSuchFieldError crash on world load w/ new MapAtlases Fabric versions

### ISSUE THREAD

**Issue by Partonetrain** [lanAnderson/SeasonInfo#63]
MapAtlases Fabric got a bit of a refactor, so SeasonHUD can no longer find the SeasonHUD config.
```
java.lang.NoSuchFieldError: CONFIG
	at club.iananderson.seasonhud.client.minimaps.MapAtlases.shouldDraw(MapAtlases.java:61)
	at club.iananderson.seasonhud.impl.minimaps.HiddenMinimap.minimapHidden(HiddenMinimap.java:29)
	at club.iananderson.seasonhud.client.SeasonHUDOverlay.onHudRender(SeasonHUDOverlay.java:53)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$cpd000$fabric-rendering-v1$render(class_329.java:6386)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by lanAnderson** [comment]
Should be fixed in version 1.7.7 that is currently uploading
