### ISSUE TITLE
Issues with MapAtlases

### ISSUE THREAD

**Issue by ayronnnn** [lanAnderson/SeasonInfo#66]
Hello, I added SeasonHUD to my Modpack, but the game crashes when launching a world. I think the issue is related to MapAtlases.
Heres what I add in my Console.

```
[21:27:06] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.NoClassDefFoundError: pepjebs/mapatlases/config/MapAtlasesClientConfig
	at club.iananderson.seasonhud.client.minimaps.MapAtlases.shouldDraw(MapAtlases.java:70) ~[seasonhud-fabric-1.20.1-1.7.8.jar:?]
	at club.iananderson.seasonhud.impl.minimaps.HiddenMinimap.minimapHidden(HiddenMinimap.java:29) ~[seasonhud-fabric-1.20.1-1.7.8.jar:?]
	at club.iananderson.seasonhud.client.SeasonHUDOverlay.onHudRender(SeasonHUDOverlay.java:53) ~[seasonhud-fabric-1.20.1-1.7.8.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27) ~[fabric-rendering-v1-3.0.7+b3afc78b77-8f03a476debd550f.jar:?]
	at net.minecraft.class_329.handler$ddf001$fabric-rendering-v1$render(class_329.java:6386) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:370) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:926) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.ClassNotFoundException: pepjebs.mapatlases.config.MapAtlasesClientConfig
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 13 more
```

**Comment by lanAnderson** [comment]
What version of MapAtlases are you using? I can't replicate it with the latest version.

**Comment by ayronnnn** [comment]
Very strange. I am using version 2.6.0 of MapAtlases. Perhaps you would like me to send you a private version of the Modpack that includes SeasonHUD so that you can check on your end with the Modrinth application?

**Comment by ayronnnn** [comment]
Resolved! Indeed, I wasn't using the latest version of MapAtlases. I hadn't thought to check the Curseforge page for the Mod, where more versions are available.
