### ISSUE TITLE
MapAtlases Incompatibility

### ISSUE THREAD

**Issue by surgeoverkill** [lanAnderson/SeasonInfo#93]
**Describe the issue**

- the game itself is able to load up fine, however when loading into a world, causes a game to crash. I'm guessing something to do with minimap hud. 

**Minecraft Version**

- 1.20.1

**Mod Version**

- I tested 1.8.6, 1.8.5, 1.8.2, 1.8.1, 1.7.19, 1.7.8

**Modloader(Fabric/Forge/NeoForge)**

- fabric

**Modloader Version**

- 0.15.11

**Additional Info (Crashlog/Modlist)**

- I tested on a vanilla game with just fabric seasons and seasonHUD, and map atlases installed, aside from dependencies. 

[18:06:47] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[18:06:48] [main/INFO]: Loading 60 mods:
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- fabric-api 0.83.1+1.20.1
	   |-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b77
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.11+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b77
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b77
	   |-- fabric-particles-v1 1.0.28+b3afc78b77
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b77
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- forgeconfigapiport 8.0.0
	- java 17
	- map_atlases 2.6.0
	- minecraft 1.20.1
	- seasonhud 1.8.6
	- seasons 2.3+1.20
[18:06:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[18:06:48] [main/INFO]: Compatibility level set to JAVA_16
[18:06:48] [main/INFO]: Compatibility level set to JAVA_17
[18:06:49] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[18:06:50] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[18:06:53] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 119 milliseconds
[18:06:55] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:06:56] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[18:06:56] [Render thread/INFO]: [Fabric Seasons] Trying to read config file...
[18:06:56] [Render thread/INFO]: [Fabric Seasons] A config file was found, loading it..
[18:06:56] [Render thread/INFO]: [Fabric Seasons] Successfully loaded config file.
[18:06:56] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[18:06:56] [Render thread/WARN]: Skipping bad option: 
[18:06:56] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[18:06:57] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-tables-v1, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-networking-v0, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, map_atlases, seasonhud, seasons)
[18:06:58] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[18:06:59] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[18:06:59] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[18:06:59] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Headphones (4- Razer Nari - Game)
[18:06:59] [Render thread/INFO]: Sound engine started
[18:06:59] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[18:06:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[18:06:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[18:06:59] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[18:06:59] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[18:06:59] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[18:06:59] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[18:06:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[18:06:59] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[18:07:00] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[18:07:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[18:07:00] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[18:07:00] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[18:07:00] [Render thread/INFO]: [Fabric Seasons] Successfully loaded 3 custom grass colors.
[18:07:00] [Render thread/INFO]: [Fabric Seasons] Successfully loaded 3 custom foliage colors.
[18:07:07] [Render thread/INFO]: Loaded 7 recipes
[18:07:08] [Render thread/INFO]: Loaded 1271 advancements
[18:07:08] [Render thread/INFO]: [Fabric Seasons] Successfully loaded 15 custom crop configs.
[18:07:10] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.642 ms
[18:07:10] [Server thread/INFO]: Starting integrated minecraft server version 1.20.1
[18:07:10] [Server thread/INFO]: Generating keypair
[18:07:12] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:07:13] [Render thread/INFO]: Preparing spawn area: 0%
[18:07:13] [Render thread/INFO]: Preparing spawn area: 0%
[18:07:13] [Render thread/INFO]: Preparing spawn area: 0%
[18:07:14] [Render thread/INFO]: Preparing spawn area: 2%
[18:07:14] [Render thread/INFO]: Preparing spawn area: 4%
[18:07:15] [Render thread/INFO]: Preparing spawn area: 6%
[18:07:15] [Render thread/INFO]: Preparing spawn area: 9%
[18:07:16] [Render thread/INFO]: Preparing spawn area: 13%
[18:07:16] [Render thread/INFO]: Preparing spawn area: 17%
[18:07:17] [Render thread/INFO]: Preparing spawn area: 21%
[18:07:17] [Render thread/INFO]: Preparing spawn area: 24%
[18:07:18] [Render thread/INFO]: Preparing spawn area: 31%
[18:07:18] [Render thread/INFO]: Preparing spawn area: 33%
[18:07:19] [Render thread/INFO]: Preparing spawn area: 39%
[18:07:19] [Render thread/INFO]: Preparing spawn area: 43%
[18:07:20] [Render thread/INFO]: Preparing spawn area: 48%
[18:07:20] [Render thread/INFO]: Preparing spawn area: 54%
[18:07:21] [Render thread/INFO]: Preparing spawn area: 58%
[18:07:21] [Render thread/INFO]: Preparing spawn area: 63%
[18:07:22] [Render thread/INFO]: Preparing spawn area: 69%
[18:07:22] [Render thread/INFO]: Preparing spawn area: 73%
[18:07:23] [Render thread/INFO]: Preparing spawn area: 79%
[18:07:23] [Render thread/INFO]: Preparing spawn area: 84%
[18:07:24] [Render thread/INFO]: Preparing spawn area: 89%
[18:07:24] [Render thread/INFO]: Preparing spawn area: 94%
[18:07:25] [Render thread/INFO]: Time elapsed: 12334 ms
[18:07:25] [Server thread/INFO]: Changing view distance to 12, from 10
[18:07:25] [Server thread/INFO]: Changing simulation distance to 12, from 0
[18:07:25] [Server thread/INFO]: {MINECRAFT_USERNAME}[local:E:35c86ee0] logged in with entity id 84 at (103.5, 72.0, -374.5)
[18:07:26] [Server thread/INFO]: {MINECRAFT_USERNAME} joined the game
[18:07:26] [Render thread/INFO]: [System] [CHAT] \nLooks like you don't have Fabric Seasons: Extras installed!\n�eGet custom items and blocks to help you on your adventure installed the addon.\n�eAvailable at: �6�nCurseForge�r �2�nModrinth�r �5�nGitHub�r\n�eThis message will only show once.\n
[18:07:26] [Render thread/INFO]: [Fabric Seasons] Received dedicated server crops.
[18:07:26] [Render thread/INFO]: Loaded 2 advancements
[18:07:27] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoClassDefFoundError: pepjebs/mapatlases/config/MapAtlasesClientConfig
	at club.iananderson.seasonhud.client.minimaps.MapAtlases.shouldDraw(MapAtlases.java:74) ~[seasonhud-fabric-1.20.1-1.8.6.jar:?]
	at club.iananderson.seasonhud.platform.FabricMinimapHelper.currentMinimapHidden(FabricMinimapHelper.java:40) ~[seasonhud-fabric-1.20.1-1.8.6.jar:?]
	at club.iananderson.seasonhud.client.SeasonHUDOverlayCommon.render(SeasonHUDOverlayCommon.java:37) ~[seasonhud-fabric-1.20.1-1.8.6.jar:?]
	at club.iananderson.seasonhud.client.SeasonHUDOverlay.onHudRender(SeasonHUDOverlay.java:20) ~[seasonhud-fabric-1.20.1-1.8.6.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27) ~[fabric-rendering-v1-3.0.6+b3afc78b77-785e07f6249e12c3.jar:?]
	at net.minecraft.class_329.handler$zhi000$fabric-rendering-v1$render(class_329.java:1386) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:370) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:926) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.ClassNotFoundException: pepjebs.mapatlases.config.MapAtlasesClientConfig
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	... 14 more
[18:07:27] [Server thread/INFO]: Stopping server
[18:07:27] [Server thread/INFO]: Saving players
[18:07:27] [Server thread/INFO]: Saving worlds
[18:07:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:07:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:07:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:07:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[18:07:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[18:07:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[18:07:29] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by lanAnderson** [comment]
It looks like you are using MapAtlases 2.6.0 still. Currently, new updates for it only get posted to CurseForge and not Modrinth. so you will need to look there for the updates. 

If you absolutely need to use v2.6.0, I believe SeasonHUD 1.7.6 was the last version that had the code for the old version and should work.
